apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solutions/python-manifests
    repoURL: https://github.com/mwinel/argocd-gitops-test.git
    targetRevision: HEAD
  syncPolicy: {}