apiVersion: v1
kind: Service
metadata:
  name: python-helloworld
  labels:
    service: python-helloworld
spec:
  selector:
    app: python-helloworld
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30009
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30010