apiVersion: v1
kind: Service
metadata:
  name: node-todos
  labels:
    service: node-todos
  namespace: demo
spec:
  selector:
    app: node-todos
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30020
    - name: https
      protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 30021