name: Update deployment file

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'solutions/node-manifests/deployment.yaml'
      - '.current-image.yaml'

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITOPS_PAT }}
        fetch-depth: 0
    
    - name: Install dependencies
      run: npm install js-yaml axios

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update file
      uses: actions/github-script@v4
      with:
        script: |
          const yaml = require('js-yaml');
          const fs = require('fs');
          const axios = require('axios');

          const path = './solutions/node-manifests/deployment.yaml'; // updated file path
          let doc = yaml.load(fs.readFileSync(path, 'utf8'));
          console.log("Original file contents:", doc); // print original file contents

          // replace 'your-image-name' with your Docker Hub image name
          const response = await axios.get('https://registry.hub.docker.com/v2/repositories/mwinel/node-kubernetes-web/tags');
          const latestTag = response.data.results[0].name;
          console.log("Latest tag:", latestTag);
          console.log("Current image:", doc.spec.template.spec.containers[0].image);

          // update the file content
          doc.spec.template.spec.containers[0].image = `mwinel/node-kubernetes-web:${latestTag}`; // replace with your new image
          let yamlStr = yaml.dump(doc);
          fs.writeFileSync(path, yamlStr, 'utf8');

          // create a file in the root folder and store the current image tag in it
          fs.writeFileSync('./.current-image.yaml', `mwinel/node-kubernetes-web:${latestTag}`, 'utf8');

          return yamlStr;

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git status
        git add solutions/node-manifests/deployment.yaml .current-image.yaml # add specific files
        git commit -am "Update image tag" || exit 0
        git push --force